# Generated by Django 5.1.5 on 2025-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Study_Name', models.CharField(max_length=100)),
                ('Study_Description', models.TextField()),
                ('Study_Phase', models.CharField(choices=[('Phase I', 'Phase I'), ('Phase II', 'Phase II'), ('Phase III', 'Phase III'), ('Phase IV', 'Phase IV')], max_length=100)),
                ('Sponser_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datas',
            },
        ),
    ]
